### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by oksie-roksie** [oksie-roksie/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Oksana-coder** [comment]
Result-oriented, driven and highly motivated entry-level programmer skilled in JavaScript is seeking to start a career in the field of Information Technology and to grow professionally and personally. Passionate about learning and applying new information. Demonstrated ability to solve problems and work under pressure in order to deliver projects on time. Proven interpersonal and communication skills while working with a variety of teams and departments.
